phpcs:
    standard: PSR2

phpmd:
    standard: app/phpmd.xml

phpcpd:
    minLines: 5
    minTokens: 70

phpstan:
    level: 0
    # paths are relative to CWD (current working directory) !!!
#    bootstrap: vendor/autoload.php 
#    autoload:
#        - tests

# paths are relative to .phpqa.yml, so don't copy-paste this section if you don't have custom templates
report:
    phploc: app/report/phploc.xsl
    phpcpd: app/report/phpcpd.xsl
    phpcs: app/report/phpcs.xsl
    pdepend: app/report/pdepend.xsl
    phpmd: app/report/phpmd.xsl
