sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install:
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - composer install --no-interaction
script:
  - vendor/phpunit/phpunit/phpunit
after_success:
  - ./phpqa --output cli --tools phploc,phpcpd,phpcs,phpmd
# http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
cache:
  directories:
    - vendor
    - $HOME/.composer/cache