sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install:
  - composer install
script:
  - vendor/phpunit/phpunit/phpunit
after_success:
  - ./phpqa --output cli --tools phploc,phpcpd,phpcs,phpmd
# http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
cache:
  directories:
    - vendor
    - $HOME/.composer/cache